-- Seed data: pilgrimage trips 2026 (11 tháng còn lại) + 2027 (11 tháng còn lại)
-- Đã có sẵn: sort_order=1 (Jul 2026), sort_order=2 (Mar 2027)
-- Chạy file này trong Supabase Dashboard → SQL Editor

INSERT INTO pilgrimage_trips (dates, title, departure, destinations, organizer, description, contact, status, sort_order)
VALUES
  -- 2026: các tháng còn lại (trừ tháng 7 đã có)
  ('10/01/2026 – 11/01/2026', 'Hành hương Tắc Sậy tháng 01/2026',
   'TP. Hồ Chí Minh', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Ban Mục Vụ Cộng Đồng',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 2),

  ('07/02/2026 – 08/02/2026', 'Hành hương Tắc Sậy tháng 02/2026',
   'Cần Thơ', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Giáo Xứ Thánh Tâm',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 3),

  ('14/03/2026 – 15/03/2026', 'Hành hương Tắc Sậy tháng 03/2026',
   'Vũng Tàu', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Hội Đoàn Tắc Sậy',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 4),

  ('11/04/2026 – 12/04/2026', 'Hành hương Tắc Sậy tháng 04/2026',
   'Đà Lạt', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Đoàn Hành Hương Miền Nam',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 5),

  ('09/05/2026 – 10/05/2026', 'Hành hương Tắc Sậy tháng 05/2026',
   'Hà Nội', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Cộng Đoàn Cha Diệp',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 6),

  ('13/06/2026 – 14/06/2026', 'Hành hương Tắc Sậy tháng 06/2026',
   'Đồng Nai', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Ban Tổ Chức Giáo Phận',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 7),

  ('08/08/2026 – 09/08/2026', 'Hành hương Tắc Sậy tháng 08/2026',
   'Bình Dương', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Ban Mục Vụ Cộng Đồng',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 8),

  ('12/09/2026 – 13/09/2026', 'Hành hương Tắc Sậy tháng 09/2026',
   'TP. Hồ Chí Minh', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Giáo Xứ Thánh Tâm',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 9),

  ('10/10/2026 – 11/10/2026', 'Hành hương Tắc Sậy tháng 10/2026',
   'Cần Thơ', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Hội Đoàn Tắc Sậy',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 10),

  ('07/11/2026 – 08/11/2026', 'Hành hương Tắc Sậy tháng 11/2026',
   'Vũng Tàu', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Đoàn Hành Hương Miền Nam',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 11),

  ('05/12/2026 – 06/12/2026', 'Hành hương Tắc Sậy tháng 12/2026',
   'Đà Lạt', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Cộng Đoàn Cha Diệp',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy, cầu nguyện qua lời bầu cử của Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 12),

  -- 2027: các tháng còn lại (trừ tháng 3 đã có)
  ('10/01/2027 – 11/01/2027', 'Hành hương Tắc Sậy tháng 01/2027',
   'TP. Hồ Chí Minh', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Ban Mục Vụ Cộng Đồng',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy đầu năm 2027. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 13),

  ('06/02/2027 – 07/02/2027', 'Hành hương Tắc Sậy tháng 02/2027',
   'Cần Thơ', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Giáo Xứ Thánh Tâm',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 14),

  ('10/04/2027 – 11/04/2027', 'Hành hương Tắc Sậy tháng 04/2027',
   'Đồng Nai', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Hội Đoàn Tắc Sậy',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 15),

  ('08/05/2027 – 09/05/2027', 'Hành hương Tắc Sậy tháng 05/2027',
   'Bình Dương', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Đoàn Hành Hương Miền Nam',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 16),

  ('12/06/2027 – 13/06/2027', 'Hành hương Tắc Sậy tháng 06/2027',
   'Vũng Tàu', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Cộng Đoàn Cha Diệp',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 17),

  ('10/07/2027 – 12/07/2027', 'Hành hương Đại Lễ Tắc Sậy tháng 07/2027',
   'TP. Hồ Chí Minh', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Ban Tổ Chức Giáo Phận',
   'Chuyến hành hương đặc biệt kính Lễ Cha Phanxicô Xaviê Trương Bửu Diệp. Hành trình 3 ngày 2 đêm, bao gồm Thánh Lễ trọng thể, viếng mộ và các nghi lễ tâm linh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 18),

  ('07/08/2027 – 08/08/2027', 'Hành hương Tắc Sậy tháng 08/2027',
   'Hà Nội', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Ban Mục Vụ Cộng Đồng',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 19),

  ('11/09/2027 – 12/09/2027', 'Hành hương Tắc Sậy tháng 09/2027',
   'Cần Thơ', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Giáo Xứ Thánh Tâm',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 20),

  ('09/10/2027 – 10/10/2027', 'Hành hương Tắc Sậy tháng 10/2027',
   'Đà Lạt', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Hội Đoàn Tắc Sậy',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 21),

  ('06/11/2027 – 07/11/2027', 'Hành hương Tắc Sậy tháng 11/2027',
   'Đồng Nai', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Đoàn Hành Hương Miền Nam',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 22),

  ('04/12/2027 – 05/12/2027', 'Hành hương Tắc Sậy tháng 12/2027',
   'TP. Hồ Chí Minh', ARRAY['Đền Thánh Tắc Sậy, Bạc Liêu'],
   'Cộng Đoàn Cha Diệp',
   'Chuyến hành hương kính viếng Đền Thánh Tắc Sậy cuối năm 2027. Hành trình 2 ngày 1 đêm, bao gồm Thánh Lễ, viếng mộ và tham quan khu đền thánh.',
   'Liên hệ: 0911 990 226 | congdong@chatruongbuudiep.com',
   'open', 23);
