
export const CONTENT_BANK = [
  {
    "format": "Bài Blog chuyên sâu",
    "iconName": "PenTool",
    "color": "text-blue-600 bg-blue-50 border-blue-200",
    "description": "Đăng Web (Thư viện/Cần biết) > 1000 chữ. Mục tiêu: Lên TOP 1 Google.",
    "articles": [
      "Tiểu sử Cha Phanxicô Trương Bửu Diệp từ lúc sinh ra đến khi tử đạo",
      "Lịch sử hình thành Trung tâm Hành hương Tắc Sậy",
      "5 điều ít người biết về cuộc đời vị mục tử nhân lành Phanxicô Trương Bửu Diệp",
      "Kinh nghiệm đi hành hương Cha Diệp từ Cần Thơ: Đi xe gì, ăn nghỉ ở đâu?",
      "Cập nhật Giờ lễ Nhà thờ Tắc Sậy mới nhất (Năm 2026)",
      "Top các nhà xe uy tín chuyên tuyến Bến Tre - Cha Diệp (Tắc Sậy)",
      "Đi hành hương Cha Diệp cần chuẩn bị những gì? Lịch trình 1 ngày 1 đêm",
      "Hướng dẫn đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp đúng cách tại nhà",
      "Giải đáp: Tại sao gọi là Cha Diệp và Nhà thờ Tắc Sậy?",
      "Nhà thờ Tắc Sậy ở đâu? Bản đồ và hướng dẫn đường đi chi tiết từ Bình Dương",
      "Câu chuyện tử đạo bi tráng của Cha Phanxicô Trương Bửu Diệp năm 1946",
      "Cẩm nang du lịch Bạc Liêu kết hợp hành hương nhà thờ Cha Diệp",
      "Tìm hiểu kiến trúc độc đáo của phần mộ Cha Phanxicô Trương Bửu Diệp",
      "Cha Phanxicô Trương Bửu Diệp là ai? Tại sao hàng triệu người đổ về Tắc Sậy?",
      "Các mốc thời gian quan trọng trong cuộc đời Cha Phanxicô Trương Bửu Diệp",
      "Những di vật còn sót lại của Cha Phanxicô Trương Bửu Diệp tại Tắc Sậy",
      "Quy trình xin lễ và đọc ý chỉ cầu nguyện tại Nhà thờ Tắc Sậy",
      "Làm sao để gửi lời chứng ơn lành lên website Cha Phanxicô Trương Bửu Diệp?",
      "Ý nghĩa của ngày giỗ Cha Diệp (12/3) đối với người Công Giáo",
      "Hướng dẫn xin nước thánh và lá thư tại nhà thờ Tắc Sậy",
      "Tiểu sử Cha Phanxicô Trương Bửu Diệp từ lúc sinh ra đến khi tử đạo (Phần 3)",
      "Lịch sử hình thành Trung tâm Hành hương Tắc Sậy (Phần 8)",
      "5 điều ít người biết về cuộc đời vị mục tử nhân lành Phanxicô Trương Bửu Diệp (Phần 9)",
      "Kinh nghiệm đi hành hương Cha Diệp từ Cà Mau: Đi xe gì, ăn nghỉ ở đâu?",
      "Cập nhật Giờ lễ Nhà thờ Tắc Sậy mới nhất (Năm 2026) (Phần 8)",
      "Top các nhà xe uy tín chuyên tuyến Đà Lạt - Cha Diệp (Tắc Sậy)",
      "Đi hành hương Cha Diệp cần chuẩn bị những gì? Lịch trình 1 ngày 1 đêm (Phần 7)",
      "Hướng dẫn đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp đúng cách tại nhà (Phần 9)",
      "Giải đáp: Tại sao gọi là Cha Diệp và Nhà thờ Tắc Sậy? (Phần 8)",
      "Nhà thờ Tắc Sậy ở đâu? Bản đồ và hướng dẫn đường đi chi tiết từ An Giang",
      "Câu chuyện tử đạo bi tráng của Cha Phanxicô Trương Bửu Diệp năm 1946 (Phần 9)",
      "Cẩm nang du lịch Bạc Liêu kết hợp hành hương nhà thờ Cha Diệp (Phần 9)",
      "Tìm hiểu kiến trúc độc đáo của phần mộ Cha Phanxicô Trương Bửu Diệp (Phần 5)",
      "Cha Phanxicô Trương Bửu Diệp là ai? Tại sao hàng triệu người đổ về Tắc Sậy? (Phần 10)",
      "Các mốc thời gian quan trọng trong cuộc đời Cha Phanxicô Trương Bửu Diệp (Phần 8)",
      "Những di vật còn sót lại của Cha Phanxicô Trương Bửu Diệp tại Tắc Sậy (Phần 3)",
      "Quy trình xin lễ và đọc ý chỉ cầu nguyện tại Nhà thờ Tắc Sậy (Phần 6)",
      "Làm sao để gửi lời chứng ơn lành lên website Cha Phanxicô Trương Bửu Diệp? (Phần 10)",
      "Ý nghĩa của ngày giỗ Cha Diệp (12/3) đối với người Công Giáo (Phần 2)",
      "Hướng dẫn xin nước thánh và lá thư tại nhà thờ Tắc Sậy (Phần 8)",
      "Tiểu sử Cha Phanxicô Trương Bửu Diệp từ lúc sinh ra đến khi tử đạo (Phần 10)",
      "Lịch sử hình thành Trung tâm Hành hương Tắc Sậy (Phần 10)",
      "5 điều ít người biết về cuộc đời vị mục tử nhân lành Phanxicô Trương Bửu Diệp (Phần 2)",
      "Kinh nghiệm đi hành hương Cha Diệp từ Cà Mau: Đi xe gì, ăn nghỉ ở đâu? (Phần 2)",
      "Cập nhật Giờ lễ Nhà thờ Tắc Sậy mới nhất (Năm 2026) (Phần 9)",
      "Top các nhà xe uy tín chuyên tuyến Trà Vinh - Cha Diệp (Tắc Sậy)",
      "Đi hành hương Cha Diệp cần chuẩn bị những gì? Lịch trình 1 ngày 1 đêm (Phần 6)",
      "Hướng dẫn đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp đúng cách tại nhà (Phần 5)",
      "Giải đáp: Tại sao gọi là Cha Diệp và Nhà thờ Tắc Sậy? (Phần 4)",
      "Nhà thờ Tắc Sậy ở đâu? Bản đồ và hướng dẫn đường đi chi tiết từ Kiên Giang",
      "Câu chuyện tử đạo bi tráng của Cha Phanxicô Trương Bửu Diệp năm 1946 (Phần 8)",
      "Cẩm nang du lịch Bạc Liêu kết hợp hành hương nhà thờ Cha Diệp (Phần 2)",
      "Tìm hiểu kiến trúc độc đáo của phần mộ Cha Phanxicô Trương Bửu Diệp (Phần 9)",
      "Cha Phanxicô Trương Bửu Diệp là ai? Tại sao hàng triệu người đổ về Tắc Sậy? (Phần 10)",
      "Các mốc thời gian quan trọng trong cuộc đời Cha Phanxicô Trương Bửu Diệp (Phần 10)",
      "Những di vật còn sót lại của Cha Phanxicô Trương Bửu Diệp tại Tắc Sậy (Phần 9)",
      "Quy trình xin lễ và đọc ý chỉ cầu nguyện tại Nhà thờ Tắc Sậy (Phần 5)",
      "Làm sao để gửi lời chứng ơn lành lên website Cha Phanxicô Trương Bửu Diệp? (Phần 7)",
      "Ý nghĩa của ngày giỗ Cha Diệp (12/3) đối với người Công Giáo (Phần 3)",
      "Hướng dẫn xin nước thánh và lá thư tại nhà thờ Tắc Sậy (Phần 8)",
      "Tiểu sử Cha Phanxicô Trương Bửu Diệp từ lúc sinh ra đến khi tử đạo (Phần 9)",
      "Lịch sử hình thành Trung tâm Hành hương Tắc Sậy (Phần 10)",
      "5 điều ít người biết về cuộc đời vị mục tử nhân lành Phanxicô Trương Bửu Diệp (Phần 8)",
      "Kinh nghiệm đi hành hương Cha Diệp từ Cà Mau: Đi xe gì, ăn nghỉ ở đâu? (Phần 4)",
      "Cập nhật Giờ lễ Nhà thờ Tắc Sậy mới nhất (Năm 2026) (Phần 4)",
      "Top các nhà xe uy tín chuyên tuyến Long An - Cha Diệp (Tắc Sậy)",
      "Đi hành hương Cha Diệp cần chuẩn bị những gì? Lịch trình 1 ngày 1 đêm (Phần 2)",
      "Hướng dẫn đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp đúng cách tại nhà (Phần 5)",
      "Giải đáp: Tại sao gọi là Cha Diệp và Nhà thờ Tắc Sậy? (Phần 2)",
      "Nhà thờ Tắc Sậy ở đâu? Bản đồ và hướng dẫn đường đi chi tiết từ Kiên Giang (Phần 5)",
      "Câu chuyện tử đạo bi tráng của Cha Phanxicô Trương Bửu Diệp năm 1946 (Phần 2)",
      "Cẩm nang du lịch Bạc Liêu kết hợp hành hương nhà thờ Cha Diệp (Phần 3)",
      "Tìm hiểu kiến trúc độc đáo của phần mộ Cha Phanxicô Trương Bửu Diệp (Phần 10)",
      "Cha Phanxicô Trương Bửu Diệp là ai? Tại sao hàng triệu người đổ về Tắc Sậy? (Phần 1)",
      "Các mốc thời gian quan trọng trong cuộc đời Cha Phanxicô Trương Bửu Diệp (Phần 2)",
      "Những di vật còn sót lại của Cha Phanxicô Trương Bửu Diệp tại Tắc Sậy (Phần 4)",
      "Quy trình xin lễ và đọc ý chỉ cầu nguyện tại Nhà thờ Tắc Sậy (Phần 9)",
      "Làm sao để gửi lời chứng ơn lành lên website Cha Phanxicô Trương Bửu Diệp? (Phần 9)",
      "Ý nghĩa của ngày giỗ Cha Diệp (12/3) đối với người Công Giáo (Phần 5)",
      "Hướng dẫn xin nước thánh và lá thư tại nhà thờ Tắc Sậy (Phần 1)",
      "Tiểu sử Cha Phanxicô Trương Bửu Diệp từ lúc sinh ra đến khi tử đạo (Phần 10)",
      "Lịch sử hình thành Trung tâm Hành hương Tắc Sậy (Phần 8)",
      "5 điều ít người biết về cuộc đời vị mục tử nhân lành Phanxicô Trương Bửu Diệp (Phần 8)",
      "Kinh nghiệm đi hành hương Cha Diệp từ Sài Gòn: Đi xe gì, ăn nghỉ ở đâu?",
      "Cập nhật Giờ lễ Nhà thờ Tắc Sậy mới nhất (Năm 2026) (Phần 8)",
      "Top các nhà xe uy tín chuyên tuyến Hà Nội - Cha Diệp (Tắc Sậy)",
      "Đi hành hương Cha Diệp cần chuẩn bị những gì? Lịch trình 1 ngày 1 đêm (Phần 5)",
      "Hướng dẫn đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp đúng cách tại nhà (Phần 2)",
      "Giải đáp: Tại sao gọi là Cha Diệp và Nhà thờ Tắc Sậy? (Phần 3)",
      "Nhà thờ Tắc Sậy ở đâu? Bản đồ và hướng dẫn đường đi chi tiết từ Cần Thơ",
      "Câu chuyện tử đạo bi tráng của Cha Phanxicô Trương Bửu Diệp năm 1946 (Phần 8)",
      "Cẩm nang du lịch Bạc Liêu kết hợp hành hương nhà thờ Cha Diệp (Phần 1)",
      "Tìm hiểu kiến trúc độc đáo của phần mộ Cha Phanxicô Trương Bửu Diệp (Phần 10)",
      "Cha Phanxicô Trương Bửu Diệp là ai? Tại sao hàng triệu người đổ về Tắc Sậy? (Phần 2)",
      "Các mốc thời gian quan trọng trong cuộc đời Cha Phanxicô Trương Bửu Diệp (Phần 4)",
      "Những di vật còn sót lại của Cha Phanxicô Trương Bửu Diệp tại Tắc Sậy (Phần 6)",
      "Quy trình xin lễ và đọc ý chỉ cầu nguyện tại Nhà thờ Tắc Sậy (Phần 7)",
      "Làm sao để gửi lời chứng ơn lành lên website Cha Phanxicô Trương Bửu Diệp? (Phần 8)",
      "Ý nghĩa của ngày giỗ Cha Diệp (12/3) đối với người Công Giáo (Phần 3)",
      "Hướng dẫn xin nước thánh và lá thư tại nhà thờ Tắc Sậy (Phần 9)",
      "Tiểu sử Cha Phanxicô Trương Bửu Diệp từ lúc sinh ra đến khi tử đạo (Phần 2)",
      "Lịch sử hình thành Trung tâm Hành hương Tắc Sậy (Phần 10)",
      "5 điều ít người biết về cuộc đời vị mục tử nhân lành Phanxicô Trương Bửu Diệp (Phần 2)",
      "Kinh nghiệm đi hành hương Cha Diệp từ Cà Mau: Đi xe gì, ăn nghỉ ở đâu? (Phần 8)",
      "Cập nhật Giờ lễ Nhà thờ Tắc Sậy mới nhất (Năm 2026) (Phần 1)",
      "Top các nhà xe uy tín chuyên tuyến Kiên Giang - Cha Diệp (Tắc Sậy)",
      "Đi hành hương Cha Diệp cần chuẩn bị những gì? Lịch trình 1 ngày 1 đêm (Phần 4)",
      "Hướng dẫn đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp đúng cách tại nhà (Phần 1)",
      "Giải đáp: Tại sao gọi là Cha Diệp và Nhà thờ Tắc Sậy? (Phần 4)",
      "Nhà thờ Tắc Sậy ở đâu? Bản đồ và hướng dẫn đường đi chi tiết từ Vũng Tàu",
      "Câu chuyện tử đạo bi tráng của Cha Phanxicô Trương Bửu Diệp năm 1946 (Phần 1)",
      "Cẩm nang du lịch Bạc Liêu kết hợp hành hương nhà thờ Cha Diệp (Phần 9)",
      "Tìm hiểu kiến trúc độc đáo của phần mộ Cha Phanxicô Trương Bửu Diệp (Phần 5)",
      "Cha Phanxicô Trương Bửu Diệp là ai? Tại sao hàng triệu người đổ về Tắc Sậy? (Phần 4)",
      "Các mốc thời gian quan trọng trong cuộc đời Cha Phanxicô Trương Bửu Diệp (Phần 1)",
      "Những di vật còn sót lại của Cha Phanxicô Trương Bửu Diệp tại Tắc Sậy (Phần 1)",
      "Quy trình xin lễ và đọc ý chỉ cầu nguyện tại Nhà thờ Tắc Sậy (Phần 8)",
      "Làm sao để gửi lời chứng ơn lành lên website Cha Phanxicô Trương Bửu Diệp? (Phần 1)",
      "Ý nghĩa của ngày giỗ Cha Diệp (12/3) đối với người Công Giáo (Phần 8)",
      "Hướng dẫn xin nước thánh và lá thư tại nhà thờ Tắc Sậy (Phần 9)",
      "Tiểu sử Cha Phanxicô Trương Bửu Diệp từ lúc sinh ra đến khi tử đạo (Phần 10)",
      "Lịch sử hình thành Trung tâm Hành hương Tắc Sậy (Phần 2)",
      "5 điều ít người biết về cuộc đời vị mục tử nhân lành Phanxicô Trương Bửu Diệp (Phần 1)",
      "Kinh nghiệm đi hành hương Cha Diệp từ Vĩnh Long: Đi xe gì, ăn nghỉ ở đâu?",
      "Cập nhật Giờ lễ Nhà thờ Tắc Sậy mới nhất (Năm 2026) (Phần 10)"
    ]
  },
  {
    "format": "Nhật ký Ơn lành",
    "iconName": "ImageIcon",
    "color": "text-green-600 bg-green-50 border-green-200",
    "description": "Đăng trên App mục \"Nhật ký ơn lành\". Kịch bản: 2 bài/ngày. Mục tiêu: Lan tỏa cảm xúc.",
    "articles": [
      "Ơn lành vượt qua bạo bệnh của gia đình ở Sài Gòn",
      "Vợ chồng hiếm muộn có tin vui sau lần đi Tắc Sậy khấn Cha",
      "Con trai cai nghiện thành công nhờ lời cầu bầu của Cha Phanxicô",
      "Bệnh viện trả về nhưng nay đã khỏe mạnh: Lời chứng từ Kiên Giang",
      "Vượt qua khủng hoảng nợ nần, làm ăn suôn sẻ nhờ Cha thương",
      "Bình an tai qua nạn khỏi trong vụ tai nạn thảm khốc nhờ đeo di vật của Cha",
      "Đậu đại học Y dược, giấc mơ thành sự thật nhờ lời khấn xin Cha Diệp",
      "Lương y nghèo được cứu sống khỏi bệnh ung thư giai đoạn cuối",
      "Tạ ơn Cha đã độ trì cho gia đình con ở Bạc Liêu vượt qua đại dịch bình an",
      "Tìm lại được người thân lưu lạc sau chuyến hành hương Tắc Sậy",
      "Ký ức của người con xa xứ: Được Cha che chở nơi đất khách quê người",
      "Gia đình hòa thuận trở lại sau nhiều năm ly tán nhờ ơn Cha Diệp",
      "Thoát khỏi căn bệnh hiểm nghèo một cách kỳ diệu tại Vĩnh Long",
      "Cha Diệp đã cứu con trai tôi khỏi cơn nguy kịch",
      "Công việc kinh doanh vực dậy thần kỳ sau chuyến hành hương Bạc Liêu",
      "Hạnh phúc mỉm cười với người mẹ đơn thân nhờ kiên tâm khấn Cha",
      "Thoát khỏi hỏa hoạn trong gang tấc nhờ lời kinh xin ơn",
      "Hành trình 10 năm ròng rã cầu xin và phép màu đã đến",
      "Tạ ơn Cha Phanxicô Trương Bửu Diệp đã chữa lành đôi mắt cho con",
      "Bình phục kỳ diệu sau ca phẫu thuật tim thập tử nhất sinh",
      "Ơn lành vượt qua bạo bệnh của gia đình ở Sóc Trăng",
      "Vợ chồng hiếm muộn có tin vui sau lần đi Tắc Sậy khấn Cha (Phần 3)",
      "Con trai cai nghiện thành công nhờ lời cầu bầu của Cha Phanxicô (Phần 7)",
      "Bệnh viện trả về nhưng nay đã khỏe mạnh: Lời chứng từ Cần Thơ",
      "Vượt qua khủng hoảng nợ nần, làm ăn suôn sẻ nhờ Cha thương (Phần 4)",
      "Bình an tai qua nạn khỏi trong vụ tai nạn thảm khốc nhờ đeo di vật của Cha (Phần 8)",
      "Đậu đại học Y dược, giấc mơ thành sự thật nhờ lời khấn xin Cha Diệp (Phần 8)",
      "Lương y nghèo được cứu sống khỏi bệnh ung thư giai đoạn cuối (Phần 9)",
      "Tạ ơn Cha đã độ trì cho gia đình con ở Hà Nội vượt qua đại dịch bình an",
      "Tìm lại được người thân lưu lạc sau chuyến hành hương Tắc Sậy (Phần 8)",
      "Ký ức của người con xa xứ: Được Cha che chở nơi đất khách quê người (Phần 5)",
      "Gia đình hòa thuận trở lại sau nhiều năm ly tán nhờ ơn Cha Diệp (Phần 5)",
      "Thoát khỏi căn bệnh hiểm nghèo một cách kỳ diệu tại An Giang",
      "Cha Diệp đã cứu con trai tôi khỏi cơn nguy kịch (Phần 2)",
      "Công việc kinh doanh vực dậy thần kỳ sau chuyến hành hương Bạc Liêu (Phần 6)",
      "Hạnh phúc mỉm cười với người mẹ đơn thân nhờ kiên tâm khấn Cha (Phần 2)",
      "Thoát khỏi hỏa hoạn trong gang tấc nhờ lời kinh xin ơn (Phần 8)",
      "Hành trình 10 năm ròng rã cầu xin và phép màu đã đến (Phần 10)",
      "Tạ ơn Cha Phanxicô Trương Bửu Diệp đã chữa lành đôi mắt cho con (Phần 6)",
      "Bình phục kỳ diệu sau ca phẫu thuật tim thập tử nhất sinh (Phần 5)",
      "Ơn lành vượt qua bạo bệnh của gia đình ở An Giang",
      "Vợ chồng hiếm muộn có tin vui sau lần đi Tắc Sậy khấn Cha (Phần 8)",
      "Con trai cai nghiện thành công nhờ lời cầu bầu của Cha Phanxicô (Phần 5)",
      "Bệnh viện trả về nhưng nay đã khỏe mạnh: Lời chứng từ Sài Gòn",
      "Vượt qua khủng hoảng nợ nần, làm ăn suôn sẻ nhờ Cha thương (Phần 6)",
      "Bình an tai qua nạn khỏi trong vụ tai nạn thảm khốc nhờ đeo di vật của Cha (Phần 1)",
      "Đậu đại học Y dược, giấc mơ thành sự thật nhờ lời khấn xin Cha Diệp (Phần 5)",
      "Lương y nghèo được cứu sống khỏi bệnh ung thư giai đoạn cuối (Phần 8)",
      "Tạ ơn Cha đã độ trì cho gia đình con ở Sài Gòn vượt qua đại dịch bình an",
      "Tìm lại được người thân lưu lạc sau chuyến hành hương Tắc Sậy (Phần 3)",
      "Ký ức của người con xa xứ: Được Cha che chở nơi đất khách quê người (Phần 1)",
      "Gia đình hòa thuận trở lại sau nhiều năm ly tán nhờ ơn Cha Diệp (Phần 6)",
      "Thoát khỏi căn bệnh hiểm nghèo một cách kỳ diệu tại Bạc Liêu",
      "Cha Diệp đã cứu con trai tôi khỏi cơn nguy kịch (Phần 10)",
      "Công việc kinh doanh vực dậy thần kỳ sau chuyến hành hương Bạc Liêu (Phần 7)",
      "Hạnh phúc mỉm cười với người mẹ đơn thân nhờ kiên tâm khấn Cha (Phần 10)",
      "Thoát khỏi hỏa hoạn trong gang tấc nhờ lời kinh xin ơn (Phần 7)",
      "Hành trình 10 năm ròng rã cầu xin và phép màu đã đến (Phần 4)",
      "Tạ ơn Cha Phanxicô Trương Bửu Diệp đã chữa lành đôi mắt cho con (Phần 5)",
      "Bình phục kỳ diệu sau ca phẫu thuật tim thập tử nhất sinh (Phần 1)",
      "Ơn lành vượt qua bạo bệnh của gia đình ở Sài Gòn (Phần 4)",
      "Vợ chồng hiếm muộn có tin vui sau lần đi Tắc Sậy khấn Cha (Phần 9)",
      "Con trai cai nghiện thành công nhờ lời cầu bầu của Cha Phanxicô (Phần 3)",
      "Bệnh viện trả về nhưng nay đã khỏe mạnh: Lời chứng từ Kiên Giang (Phần 6)",
      "Vượt qua khủng hoảng nợ nần, làm ăn suôn sẻ nhờ Cha thương (Phần 7)",
      "Bình an tai qua nạn khỏi trong vụ tai nạn thảm khốc nhờ đeo di vật của Cha (Phần 4)",
      "Đậu đại học Y dược, giấc mơ thành sự thật nhờ lời khấn xin Cha Diệp (Phần 3)",
      "Lương y nghèo được cứu sống khỏi bệnh ung thư giai đoạn cuối (Phần 2)",
      "Tạ ơn Cha đã độ trì cho gia đình con ở Đồng Nai vượt qua đại dịch bình an",
      "Tìm lại được người thân lưu lạc sau chuyến hành hương Tắc Sậy (Phần 2)",
      "Ký ức của người con xa xứ: Được Cha che chở nơi đất khách quê người (Phần 6)",
      "Gia đình hòa thuận trở lại sau nhiều năm ly tán nhờ ơn Cha Diệp (Phần 4)",
      "Thoát khỏi căn bệnh hiểm nghèo một cách kỳ diệu tại Đồng Nai",
      "Cha Diệp đã cứu con trai tôi khỏi cơn nguy kịch (Phần 5)",
      "Công việc kinh doanh vực dậy thần kỳ sau chuyến hành hương Bạc Liêu (Phần 8)",
      "Hạnh phúc mỉm cười với người mẹ đơn thân nhờ kiên tâm khấn Cha (Phần 6)",
      "Thoát khỏi hỏa hoạn trong gang tấc nhờ lời kinh xin ơn (Phần 10)",
      "Hành trình 10 năm ròng rã cầu xin và phép màu đã đến (Phần 8)",
      "Tạ ơn Cha Phanxicô Trương Bửu Diệp đã chữa lành đôi mắt cho con (Phần 10)",
      "Bình phục kỳ diệu sau ca phẫu thuật tim thập tử nhất sinh (Phần 2)",
      "Ơn lành vượt qua bạo bệnh của gia đình ở Đồng Nai",
      "Vợ chồng hiếm muộn có tin vui sau lần đi Tắc Sậy khấn Cha (Phần 1)",
      "Con trai cai nghiện thành công nhờ lời cầu bầu của Cha Phanxicô (Phần 5)",
      "Bệnh viện trả về nhưng nay đã khỏe mạnh: Lời chứng từ Vũng Tàu",
      "Vượt qua khủng hoảng nợ nần, làm ăn suôn sẻ nhờ Cha thương (Phần 4)",
      "Bình an tai qua nạn khỏi trong vụ tai nạn thảm khốc nhờ đeo di vật của Cha (Phần 9)",
      "Đậu đại học Y dược, giấc mơ thành sự thật nhờ lời khấn xin Cha Diệp (Phần 1)",
      "Lương y nghèo được cứu sống khỏi bệnh ung thư giai đoạn cuối (Phần 3)",
      "Tạ ơn Cha đã độ trì cho gia đình con ở Tiền Giang vượt qua đại dịch bình an",
      "Tìm lại được người thân lưu lạc sau chuyến hành hương Tắc Sậy (Phần 5)",
      "Ký ức của người con xa xứ: Được Cha che chở nơi đất khách quê người (Phần 10)",
      "Gia đình hòa thuận trở lại sau nhiều năm ly tán nhờ ơn Cha Diệp (Phần 8)",
      "Thoát khỏi căn bệnh hiểm nghèo một cách kỳ diệu tại Bình Dương",
      "Cha Diệp đã cứu con trai tôi khỏi cơn nguy kịch (Phần 4)",
      "Công việc kinh doanh vực dậy thần kỳ sau chuyến hành hương Bạc Liêu (Phần 8)",
      "Hạnh phúc mỉm cười với người mẹ đơn thân nhờ kiên tâm khấn Cha (Phần 1)",
      "Thoát khỏi hỏa hoạn trong gang tấc nhờ lời kinh xin ơn (Phần 9)",
      "Hành trình 10 năm ròng rã cầu xin và phép màu đã đến (Phần 1)",
      "Tạ ơn Cha Phanxicô Trương Bửu Diệp đã chữa lành đôi mắt cho con (Phần 9)",
      "Bình phục kỳ diệu sau ca phẫu thuật tim thập tử nhất sinh (Phần 2)",
      "Ơn lành vượt qua bạo bệnh của gia đình ở Vĩnh Long",
      "Vợ chồng hiếm muộn có tin vui sau lần đi Tắc Sậy khấn Cha (Phần 5)",
      "Con trai cai nghiện thành công nhờ lời cầu bầu của Cha Phanxicô (Phần 2)",
      "Bệnh viện trả về nhưng nay đã khỏe mạnh: Lời chứng từ Cà Mau",
      "Vượt qua khủng hoảng nợ nần, làm ăn suôn sẻ nhờ Cha thương (Phần 9)",
      "Bình an tai qua nạn khỏi trong vụ tai nạn thảm khốc nhờ đeo di vật của Cha (Phần 10)",
      "Đậu đại học Y dược, giấc mơ thành sự thật nhờ lời khấn xin Cha Diệp (Phần 8)",
      "Lương y nghèo được cứu sống khỏi bệnh ung thư giai đoạn cuối (Phần 10)",
      "Tạ ơn Cha đã độ trì cho gia đình con ở Đà Lạt vượt qua đại dịch bình an",
      "Tìm lại được người thân lưu lạc sau chuyến hành hương Tắc Sậy (Phần 10)",
      "Ký ức của người con xa xứ: Được Cha che chở nơi đất khách quê người (Phần 1)",
      "Gia đình hòa thuận trở lại sau nhiều năm ly tán nhờ ơn Cha Diệp (Phần 8)",
      "Thoát khỏi căn bệnh hiểm nghèo một cách kỳ diệu tại Vĩnh Long (Phần 2)",
      "Cha Diệp đã cứu con trai tôi khỏi cơn nguy kịch (Phần 9)",
      "Công việc kinh doanh vực dậy thần kỳ sau chuyến hành hương Bạc Liêu (Phần 5)",
      "Hạnh phúc mỉm cười với người mẹ đơn thân nhờ kiên tâm khấn Cha (Phần 6)",
      "Thoát khỏi hỏa hoạn trong gang tấc nhờ lời kinh xin ơn (Phần 9)",
      "Hành trình 10 năm ròng rã cầu xin và phép màu đã đến (Phần 3)",
      "Tạ ơn Cha Phanxicô Trương Bửu Diệp đã chữa lành đôi mắt cho con (Phần 4)",
      "Bình phục kỳ diệu sau ca phẫu thuật tim thập tử nhất sinh (Phần 10)",
      "Ơn lành vượt qua bạo bệnh của gia đình ở Cần Thơ",
      "Vợ chồng hiếm muộn có tin vui sau lần đi Tắc Sậy khấn Cha (Phần 10)",
      "Con trai cai nghiện thành công nhờ lời cầu bầu của Cha Phanxicô (Phần 4)",
      "Bệnh viện trả về nhưng nay đã khỏe mạnh: Lời chứng từ Trà Vinh",
      "Vượt qua khủng hoảng nợ nần, làm ăn suôn sẻ nhờ Cha thương (Phần 10)"
    ]
  },
  {
    "format": "Bài Post Mạng Xã Hội",
    "iconName": "Share2",
    "color": "text-purple-600 bg-purple-50 border-purple-200",
    "description": "Đăng lúc 20:00. Mục tiêu: Kéo tương tác, Share, Tăng nhận diện.",
    "articles": [
      "\"Lạy Cha, xin thương nhậm lời chúng con...\" Hiệp ý cầu nguyện tối nay cùng cộng đồng Sài Gòn",
      "Mời bà con cùng dâng 1 Kinh Kính Mừng xin ơn bình an cho gia đình",
      "\"Tôi sống giữa đoàn chiên, và nếu có chết cũng chết giữa đoàn chiên...\"",
      "Giao phó mọi lo âu cho Chúa qua lời cầu bầu của Cha Diệp, bạn sẽ thấy bình an",
      "[Góc Tạ Ơn] Giọt nước mắt hạnh phúc của người mẹ hiếm muộn ở Vũng Tàu.",
      "[Thông báo] Lịch thánh lễ Chúa Nhật tuần này tại Giáo xứ Tắc Sậy",
      "Cùng nhìn lại hình ảnh đẹp của đoàn hành hương từ Sóc Trăng sáng nay",
      "Bạn đã từng đến viếng mộ Cha Diệp chưa? Hãy chia sẻ cảm xúc của bạn nhé!",
      "Gửi một lời nguyện ước của bạn xuống phần bình luận, cộng đồng sẽ hiệp ý cầu nguyện.",
      "Một ngày bình yên tại Tắc Sậy... Chúc cộng đồng một buổi tối an lành!",
      "Cha Phanxicô Trương Bửu Diệp luôn lắng nghe lời nguyện cầu thành tâm của bạn.",
      "Hôm nay bạn có chuyện buồn? Hãy tâm sự cùng Cha nhé.",
      "Chia sẻ bài viết này để lan tỏa phép lạ của Cha đến những ai đang cần điểm tựa.",
      "Tháng mới bình an, nguyện xin Cha ban phước lành cho mọi nhà.",
      "Những vần thơ tạ ơn Cha Diệp lay động lòng người.",
      "Bạn nhớ nhất điều gì trong chuyến đi Tắc Sậy vừa qua?",
      "Hãy luôn giữ vững niềm tin, vì Cha luôn đồng hành cùng chúng ta.",
      "Hướng về Tắc Sậy - Lời kinh dâng Cha tối nay.",
      "Một hình ảnh tuyệt đẹp của nhà thờ Tắc Sậy trong ráng chiều.",
      "Đừng bỏ cuộc, vì phép màu luôn dành cho người biết hy vọng và cầu nguyện.",
      "\"Lạy Cha, xin thương nhậm lời chúng con...\" Hiệp ý cầu nguyện tối nay cùng cộng đồng Long An",
      "Mời bà con cùng dâng 1 Kinh Kính Mừng xin ơn bình an cho gia đình (Phần 8)",
      "\"Tôi sống giữa đoàn chiên, và nếu có chết cũng chết giữa đoàn chiên...\" (Phần 10)",
      "Giao phó mọi lo âu cho Chúa qua lời cầu bầu của Cha Diệp, bạn sẽ thấy bình an (Phần 3)",
      "[Góc Tạ Ơn] Giọt nước mắt hạnh phúc của người mẹ hiếm muộn ở An Giang.",
      "[Thông báo] Lịch thánh lễ Chúa Nhật tuần này tại Giáo xứ Tắc Sậy (Phần 6)",
      "Cùng nhìn lại hình ảnh đẹp của đoàn hành hương từ Hà Nội sáng nay",
      "Bạn đã từng đến viếng mộ Cha Diệp chưa? Hãy chia sẻ cảm xúc của bạn nhé! (Phần 7)",
      "Gửi một lời nguyện ước của bạn xuống phần bình luận, cộng đồng sẽ hiệp ý cầu nguyện. (Phần 4)",
      "Một ngày bình yên tại Tắc Sậy... Chúc cộng đồng một buổi tối an lành! (Phần 5)",
      "Cha Phanxicô Trương Bửu Diệp luôn lắng nghe lời nguyện cầu thành tâm của bạn. (Phần 9)",
      "Hôm nay bạn có chuyện buồn? Hãy tâm sự cùng Cha nhé. (Phần 9)",
      "Chia sẻ bài viết này để lan tỏa phép lạ của Cha đến những ai đang cần điểm tựa. (Phần 9)",
      "Tháng mới bình an, nguyện xin Cha ban phước lành cho mọi nhà. (Phần 3)",
      "Những vần thơ tạ ơn Cha Diệp lay động lòng người. (Phần 4)",
      "Bạn nhớ nhất điều gì trong chuyến đi Tắc Sậy vừa qua? (Phần 10)",
      "Hãy luôn giữ vững niềm tin, vì Cha luôn đồng hành cùng chúng ta. (Phần 9)",
      "Hướng về Tắc Sậy - Lời kinh dâng Cha tối nay. (Phần 5)",
      "Một hình ảnh tuyệt đẹp của nhà thờ Tắc Sậy trong ráng chiều. (Phần 2)",
      "Đừng bỏ cuộc, vì phép màu luôn dành cho người biết hy vọng và cầu nguyện. (Phần 7)",
      "\"Lạy Cha, xin thương nhậm lời chúng con...\" Hiệp ý cầu nguyện tối nay cùng cộng đồng Bình Dương",
      "Mời bà con cùng dâng 1 Kinh Kính Mừng xin ơn bình an cho gia đình (Phần 9)",
      "\"Tôi sống giữa đoàn chiên, và nếu có chết cũng chết giữa đoàn chiên...\" (Phần 6)",
      "Giao phó mọi lo âu cho Chúa qua lời cầu bầu của Cha Diệp, bạn sẽ thấy bình an (Phần 9)",
      "[Góc Tạ Ơn] Giọt nước mắt hạnh phúc của người mẹ hiếm muộn ở Tiền Giang.",
      "[Thông báo] Lịch thánh lễ Chúa Nhật tuần này tại Giáo xứ Tắc Sậy (Phần 7)",
      "Cùng nhìn lại hình ảnh đẹp của đoàn hành hương từ Long An sáng nay",
      "Bạn đã từng đến viếng mộ Cha Diệp chưa? Hãy chia sẻ cảm xúc của bạn nhé! (Phần 7)",
      "Gửi một lời nguyện ước của bạn xuống phần bình luận, cộng đồng sẽ hiệp ý cầu nguyện. (Phần 4)",
      "Một ngày bình yên tại Tắc Sậy... Chúc cộng đồng một buổi tối an lành! (Phần 3)",
      "Cha Phanxicô Trương Bửu Diệp luôn lắng nghe lời nguyện cầu thành tâm của bạn. (Phần 9)",
      "Hôm nay bạn có chuyện buồn? Hãy tâm sự cùng Cha nhé. (Phần 4)",
      "Chia sẻ bài viết này để lan tỏa phép lạ của Cha đến những ai đang cần điểm tựa. (Phần 2)",
      "Tháng mới bình an, nguyện xin Cha ban phước lành cho mọi nhà. (Phần 7)",
      "Những vần thơ tạ ơn Cha Diệp lay động lòng người. (Phần 3)",
      "Bạn nhớ nhất điều gì trong chuyến đi Tắc Sậy vừa qua? (Phần 4)",
      "Hãy luôn giữ vững niềm tin, vì Cha luôn đồng hành cùng chúng ta. (Phần 4)",
      "Hướng về Tắc Sậy - Lời kinh dâng Cha tối nay. (Phần 3)",
      "Một hình ảnh tuyệt đẹp của nhà thờ Tắc Sậy trong ráng chiều. (Phần 7)",
      "Đừng bỏ cuộc, vì phép màu luôn dành cho người biết hy vọng và cầu nguyện. (Phần 2)",
      "\"Lạy Cha, xin thương nhậm lời chúng con...\" Hiệp ý cầu nguyện tối nay cùng cộng đồng Kiên Giang",
      "Mời bà con cùng dâng 1 Kinh Kính Mừng xin ơn bình an cho gia đình (Phần 6)",
      "\"Tôi sống giữa đoàn chiên, và nếu có chết cũng chết giữa đoàn chiên...\" (Phần 7)",
      "Giao phó mọi lo âu cho Chúa qua lời cầu bầu của Cha Diệp, bạn sẽ thấy bình an (Phần 10)",
      "[Góc Tạ Ơn] Giọt nước mắt hạnh phúc của người mẹ hiếm muộn ở Sóc Trăng.",
      "[Thông báo] Lịch thánh lễ Chúa Nhật tuần này tại Giáo xứ Tắc Sậy (Phần 1)",
      "Cùng nhìn lại hình ảnh đẹp của đoàn hành hương từ Vũng Tàu sáng nay",
      "Bạn đã từng đến viếng mộ Cha Diệp chưa? Hãy chia sẻ cảm xúc của bạn nhé! (Phần 10)",
      "Gửi một lời nguyện ước của bạn xuống phần bình luận, cộng đồng sẽ hiệp ý cầu nguyện. (Phần 6)",
      "Một ngày bình yên tại Tắc Sậy... Chúc cộng đồng một buổi tối an lành! (Phần 6)",
      "Cha Phanxicô Trương Bửu Diệp luôn lắng nghe lời nguyện cầu thành tâm của bạn. (Phần 6)",
      "Hôm nay bạn có chuyện buồn? Hãy tâm sự cùng Cha nhé. (Phần 10)",
      "Chia sẻ bài viết này để lan tỏa phép lạ của Cha đến những ai đang cần điểm tựa. (Phần 9)",
      "Tháng mới bình an, nguyện xin Cha ban phước lành cho mọi nhà. (Phần 1)",
      "Những vần thơ tạ ơn Cha Diệp lay động lòng người. (Phần 10)",
      "Bạn nhớ nhất điều gì trong chuyến đi Tắc Sậy vừa qua? (Phần 8)",
      "Hãy luôn giữ vững niềm tin, vì Cha luôn đồng hành cùng chúng ta. (Phần 8)",
      "Hướng về Tắc Sậy - Lời kinh dâng Cha tối nay. (Phần 8)",
      "Một hình ảnh tuyệt đẹp của nhà thờ Tắc Sậy trong ráng chiều. (Phần 3)",
      "Đừng bỏ cuộc, vì phép màu luôn dành cho người biết hy vọng và cầu nguyện. (Phần 7)",
      "\"Lạy Cha, xin thương nhậm lời chúng con...\" Hiệp ý cầu nguyện tối nay cùng cộng đồng Sài Gòn (Phần 1)",
      "Mời bà con cùng dâng 1 Kinh Kính Mừng xin ơn bình an cho gia đình (Phần 4)",
      "\"Tôi sống giữa đoàn chiên, và nếu có chết cũng chết giữa đoàn chiên...\" (Phần 8)",
      "Giao phó mọi lo âu cho Chúa qua lời cầu bầu của Cha Diệp, bạn sẽ thấy bình an (Phần 5)",
      "[Góc Tạ Ơn] Giọt nước mắt hạnh phúc của người mẹ hiếm muộn ở Long An.",
      "[Thông báo] Lịch thánh lễ Chúa Nhật tuần này tại Giáo xứ Tắc Sậy (Phần 6)",
      "Cùng nhìn lại hình ảnh đẹp của đoàn hành hương từ An Giang sáng nay",
      "Bạn đã từng đến viếng mộ Cha Diệp chưa? Hãy chia sẻ cảm xúc của bạn nhé! (Phần 9)",
      "Gửi một lời nguyện ước của bạn xuống phần bình luận, cộng đồng sẽ hiệp ý cầu nguyện. (Phần 2)",
      "Một ngày bình yên tại Tắc Sậy... Chúc cộng đồng một buổi tối an lành! (Phần 10)",
      "Cha Phanxicô Trương Bửu Diệp luôn lắng nghe lời nguyện cầu thành tâm của bạn. (Phần 2)",
      "Hôm nay bạn có chuyện buồn? Hãy tâm sự cùng Cha nhé. (Phần 9)",
      "Chia sẻ bài viết này để lan tỏa phép lạ của Cha đến những ai đang cần điểm tựa. (Phần 8)",
      "Tháng mới bình an, nguyện xin Cha ban phước lành cho mọi nhà. (Phần 9)",
      "Những vần thơ tạ ơn Cha Diệp lay động lòng người. (Phần 6)",
      "Bạn nhớ nhất điều gì trong chuyến đi Tắc Sậy vừa qua? (Phần 1)",
      "Hãy luôn giữ vững niềm tin, vì Cha luôn đồng hành cùng chúng ta. (Phần 2)",
      "Hướng về Tắc Sậy - Lời kinh dâng Cha tối nay. (Phần 8)",
      "Một hình ảnh tuyệt đẹp của nhà thờ Tắc Sậy trong ráng chiều. (Phần 5)",
      "Đừng bỏ cuộc, vì phép màu luôn dành cho người biết hy vọng và cầu nguyện. (Phần 7)",
      "\"Lạy Cha, xin thương nhậm lời chúng con...\" Hiệp ý cầu nguyện tối nay cùng cộng đồng Sóc Trăng",
      "Mời bà con cùng dâng 1 Kinh Kính Mừng xin ơn bình an cho gia đình (Phần 6)",
      "\"Tôi sống giữa đoàn chiên, và nếu có chết cũng chết giữa đoàn chiên...\" (Phần 2)",
      "Giao phó mọi lo âu cho Chúa qua lời cầu bầu của Cha Diệp, bạn sẽ thấy bình an (Phần 9)",
      "[Góc Tạ Ơn] Giọt nước mắt hạnh phúc của người mẹ hiếm muộn ở Sóc Trăng. (Phần 6)",
      "[Thông báo] Lịch thánh lễ Chúa Nhật tuần này tại Giáo xứ Tắc Sậy (Phần 1)",
      "Cùng nhìn lại hình ảnh đẹp của đoàn hành hương từ Tiền Giang sáng nay",
      "Bạn đã từng đến viếng mộ Cha Diệp chưa? Hãy chia sẻ cảm xúc của bạn nhé! (Phần 5)",
      "Gửi một lời nguyện ước của bạn xuống phần bình luận, cộng đồng sẽ hiệp ý cầu nguyện. (Phần 3)",
      "Một ngày bình yên tại Tắc Sậy... Chúc cộng đồng một buổi tối an lành! (Phần 4)",
      "Cha Phanxicô Trương Bửu Diệp luôn lắng nghe lời nguyện cầu thành tâm của bạn. (Phần 1)",
      "Hôm nay bạn có chuyện buồn? Hãy tâm sự cùng Cha nhé. (Phần 2)",
      "Chia sẻ bài viết này để lan tỏa phép lạ của Cha đến những ai đang cần điểm tựa. (Phần 10)",
      "Tháng mới bình an, nguyện xin Cha ban phước lành cho mọi nhà. (Phần 1)",
      "Những vần thơ tạ ơn Cha Diệp lay động lòng người. (Phần 4)",
      "Bạn nhớ nhất điều gì trong chuyến đi Tắc Sậy vừa qua? (Phần 10)",
      "Hãy luôn giữ vững niềm tin, vì Cha luôn đồng hành cùng chúng ta. (Phần 4)",
      "Hướng về Tắc Sậy - Lời kinh dâng Cha tối nay. (Phần 3)",
      "Một hình ảnh tuyệt đẹp của nhà thờ Tắc Sậy trong ráng chiều. (Phần 6)",
      "Đừng bỏ cuộc, vì phép màu luôn dành cho người biết hy vọng và cầu nguyện. (Phần 1)",
      "\"Lạy Cha, xin thương nhậm lời chúng con...\" Hiệp ý cầu nguyện tối nay cùng cộng đồng Hà Nội",
      "Mời bà con cùng dâng 1 Kinh Kính Mừng xin ơn bình an cho gia đình (Phần 10)",
      "\"Tôi sống giữa đoàn chiên, và nếu có chết cũng chết giữa đoàn chiên...\" (Phần 5)",
      "Giao phó mọi lo âu cho Chúa qua lời cầu bầu của Cha Diệp, bạn sẽ thấy bình an (Phần 1)",
      "[Góc Tạ Ơn] Giọt nước mắt hạnh phúc của người mẹ hiếm muộn ở Vĩnh Long."
    ]
  },
  {
    "format": "Video ngắn (Tiktok/Reels)",
    "iconName": "Video",
    "color": "text-orange-600 bg-orange-50 border-orange-200",
    "description": "Video dọc < 60s. Góc quay đẹp, lồng nhạc. Mục tiêu: Virality (Lan truyền).",
    "articles": [
      "[Video] Toàn cảnh Nhà thờ Tắc Sậy nhìn từ Flycam hoàng hôn",
      "[Video] 10 giây bình an: Tiếng chuông nhà thờ Tắc Sậy buổi chiều tà",
      "[Video] Cận cảnh những bức thư tạ ơn dán đầy quanh mộ Cha",
      "[Video] Chuyện thật 100%: Lương y nghèo được cứu sống khỏi bạo bệnh thần kỳ",
      "[Video] Lần đầu đi Tắc Sậy xin ơn: Cần chuẩn bị kinh đọc gì?",
      "[Video] Hướng dẫn đăng ký xe đi hành hương nhà thờ Cha Diệp ngay trên điện thoại",
      "[Video] Hướng dẫn điền form gửi Nhật ký Ơn lành trên Website",
      "[Video] Cảm động: Lời chia sẻ của đoàn người từ Vũng Tàu đi từ 4h sáng đến viếng Cha",
      "[Video] Review nhà khách Tắc Sậy: Tiện nghi, sạch sẽ và an bình",
      "[Video] Sự tích bức tượng Cha Diệp hiền từ tại khuôn viên nhà thờ",
      "[Video] Theo chân đoàn hành hương Bến Tre khám phá ẩm thực quanh nhà thờ",
      "[Video] Lời khuyên cho người lớn tuổi khi đi hành hương Tắc Sậy",
      "[Video] Khoảnh khắc linh thiêng trong Thánh lễ tại nhà thờ Cha Diệp",
      "[Video] Cùng đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp (Bản chuẩn)",
      "[Video] Lắng nghe ca khúc tạ ơn Cha Diệp hay nhất",
      "[Video] Hành trình xe khách đêm từ Bạc Liêu đi Bạc Liêu",
      "[Video] Những lưu ý quan trọng khi vào viếng phần mộ Cha Diệp",
      "[Video] Kiến trúc độc đáo của gian cung thánh nhà thờ Tắc Sậy",
      "[Video] Phỏng vấn: Niềm tin mãnh liệt của bà con lương dân dành cho Cha",
      "[Video] Chào buổi sáng Tắc Sậy - Khung cảnh bình minh thanh tịnh",
      "[Video] Toàn cảnh Nhà thờ Tắc Sậy nhìn từ Flycam hoàng hôn (Phần 8)",
      "[Video] 10 giây bình an: Tiếng chuông nhà thờ Tắc Sậy buổi chiều tà (Phần 2)",
      "[Video] Cận cảnh những bức thư tạ ơn dán đầy quanh mộ Cha (Phần 6)",
      "[Video] Chuyện thật 100%: Lương y nghèo được cứu sống khỏi bạo bệnh thần kỳ (Phần 1)",
      "[Video] Lần đầu đi Tắc Sậy xin ơn: Cần chuẩn bị kinh đọc gì? (Phần 1)",
      "[Video] Hướng dẫn đăng ký xe đi hành hương nhà thờ Cha Diệp ngay trên điện thoại (Phần 1)",
      "[Video] Hướng dẫn điền form gửi Nhật ký Ơn lành trên Website (Phần 4)",
      "[Video] Cảm động: Lời chia sẻ của đoàn người từ Hà Nội đi từ 4h sáng đến viếng Cha",
      "[Video] Review nhà khách Tắc Sậy: Tiện nghi, sạch sẽ và an bình (Phần 4)",
      "[Video] Sự tích bức tượng Cha Diệp hiền từ tại khuôn viên nhà thờ (Phần 1)",
      "[Video] Theo chân đoàn hành hương Đà Lạt khám phá ẩm thực quanh nhà thờ",
      "[Video] Lời khuyên cho người lớn tuổi khi đi hành hương Tắc Sậy (Phần 1)",
      "[Video] Khoảnh khắc linh thiêng trong Thánh lễ tại nhà thờ Cha Diệp (Phần 5)",
      "[Video] Cùng đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp (Bản chuẩn) (Phần 10)",
      "[Video] Lắng nghe ca khúc tạ ơn Cha Diệp hay nhất (Phần 7)",
      "[Video] Hành trình xe khách đêm từ Sài Gòn đi Bạc Liêu",
      "[Video] Những lưu ý quan trọng khi vào viếng phần mộ Cha Diệp (Phần 1)",
      "[Video] Kiến trúc độc đáo của gian cung thánh nhà thờ Tắc Sậy (Phần 3)",
      "[Video] Phỏng vấn: Niềm tin mãnh liệt của bà con lương dân dành cho Cha (Phần 5)",
      "[Video] Chào buổi sáng Tắc Sậy - Khung cảnh bình minh thanh tịnh (Phần 1)",
      "[Video] Toàn cảnh Nhà thờ Tắc Sậy nhìn từ Flycam hoàng hôn (Phần 5)",
      "[Video] 10 giây bình an: Tiếng chuông nhà thờ Tắc Sậy buổi chiều tà (Phần 3)",
      "[Video] Cận cảnh những bức thư tạ ơn dán đầy quanh mộ Cha (Phần 4)",
      "[Video] Chuyện thật 100%: Lương y nghèo được cứu sống khỏi bạo bệnh thần kỳ (Phần 8)",
      "[Video] Lần đầu đi Tắc Sậy xin ơn: Cần chuẩn bị kinh đọc gì? (Phần 6)",
      "[Video] Hướng dẫn đăng ký xe đi hành hương nhà thờ Cha Diệp ngay trên điện thoại (Phần 9)",
      "[Video] Hướng dẫn điền form gửi Nhật ký Ơn lành trên Website (Phần 1)",
      "[Video] Cảm động: Lời chia sẻ của đoàn người từ Vũng Tàu đi từ 4h sáng đến viếng Cha (Phần 2)",
      "[Video] Review nhà khách Tắc Sậy: Tiện nghi, sạch sẽ và an bình (Phần 6)",
      "[Video] Sự tích bức tượng Cha Diệp hiền từ tại khuôn viên nhà thờ (Phần 10)",
      "[Video] Theo chân đoàn hành hương Sài Gòn khám phá ẩm thực quanh nhà thờ",
      "[Video] Lời khuyên cho người lớn tuổi khi đi hành hương Tắc Sậy (Phần 5)",
      "[Video] Khoảnh khắc linh thiêng trong Thánh lễ tại nhà thờ Cha Diệp (Phần 2)",
      "[Video] Cùng đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp (Bản chuẩn) (Phần 10)",
      "[Video] Lắng nghe ca khúc tạ ơn Cha Diệp hay nhất (Phần 6)",
      "[Video] Hành trình xe khách đêm từ Sóc Trăng đi Bạc Liêu",
      "[Video] Những lưu ý quan trọng khi vào viếng phần mộ Cha Diệp (Phần 9)",
      "[Video] Kiến trúc độc đáo của gian cung thánh nhà thờ Tắc Sậy (Phần 9)",
      "[Video] Phỏng vấn: Niềm tin mãnh liệt của bà con lương dân dành cho Cha (Phần 2)",
      "[Video] Chào buổi sáng Tắc Sậy - Khung cảnh bình minh thanh tịnh (Phần 7)",
      "[Video] Toàn cảnh Nhà thờ Tắc Sậy nhìn từ Flycam hoàng hôn (Phần 1)",
      "[Video] 10 giây bình an: Tiếng chuông nhà thờ Tắc Sậy buổi chiều tà (Phần 1)",
      "[Video] Cận cảnh những bức thư tạ ơn dán đầy quanh mộ Cha (Phần 5)",
      "[Video] Chuyện thật 100%: Lương y nghèo được cứu sống khỏi bạo bệnh thần kỳ (Phần 4)",
      "[Video] Lần đầu đi Tắc Sậy xin ơn: Cần chuẩn bị kinh đọc gì? (Phần 9)",
      "[Video] Hướng dẫn đăng ký xe đi hành hương nhà thờ Cha Diệp ngay trên điện thoại (Phần 10)",
      "[Video] Hướng dẫn điền form gửi Nhật ký Ơn lành trên Website (Phần 1)",
      "[Video] Cảm động: Lời chia sẻ của đoàn người từ Đà Lạt đi từ 4h sáng đến viếng Cha",
      "[Video] Review nhà khách Tắc Sậy: Tiện nghi, sạch sẽ và an bình (Phần 6)",
      "[Video] Sự tích bức tượng Cha Diệp hiền từ tại khuôn viên nhà thờ (Phần 4)",
      "[Video] Theo chân đoàn hành hương Tiền Giang khám phá ẩm thực quanh nhà thờ",
      "[Video] Lời khuyên cho người lớn tuổi khi đi hành hương Tắc Sậy (Phần 5)",
      "[Video] Khoảnh khắc linh thiêng trong Thánh lễ tại nhà thờ Cha Diệp (Phần 2)",
      "[Video] Cùng đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp (Bản chuẩn) (Phần 7)",
      "[Video] Lắng nghe ca khúc tạ ơn Cha Diệp hay nhất (Phần 10)",
      "[Video] Hành trình xe khách đêm từ Bình Dương đi Bạc Liêu",
      "[Video] Những lưu ý quan trọng khi vào viếng phần mộ Cha Diệp (Phần 6)",
      "[Video] Kiến trúc độc đáo của gian cung thánh nhà thờ Tắc Sậy (Phần 9)",
      "[Video] Phỏng vấn: Niềm tin mãnh liệt của bà con lương dân dành cho Cha (Phần 1)",
      "[Video] Chào buổi sáng Tắc Sậy - Khung cảnh bình minh thanh tịnh (Phần 4)",
      "[Video] Toàn cảnh Nhà thờ Tắc Sậy nhìn từ Flycam hoàng hôn (Phần 10)",
      "[Video] 10 giây bình an: Tiếng chuông nhà thờ Tắc Sậy buổi chiều tà (Phần 9)",
      "[Video] Cận cảnh những bức thư tạ ơn dán đầy quanh mộ Cha (Phần 10)",
      "[Video] Chuyện thật 100%: Lương y nghèo được cứu sống khỏi bạo bệnh thần kỳ (Phần 9)",
      "[Video] Lần đầu đi Tắc Sậy xin ơn: Cần chuẩn bị kinh đọc gì? (Phần 7)",
      "[Video] Hướng dẫn đăng ký xe đi hành hương nhà thờ Cha Diệp ngay trên điện thoại (Phần 7)",
      "[Video] Hướng dẫn điền form gửi Nhật ký Ơn lành trên Website (Phần 9)",
      "[Video] Cảm động: Lời chia sẻ của đoàn người từ Trà Vinh đi từ 4h sáng đến viếng Cha",
      "[Video] Review nhà khách Tắc Sậy: Tiện nghi, sạch sẽ và an bình (Phần 4)",
      "[Video] Sự tích bức tượng Cha Diệp hiền từ tại khuôn viên nhà thờ (Phần 2)",
      "[Video] Theo chân đoàn hành hương Tiền Giang khám phá ẩm thực quanh nhà thờ (Phần 4)",
      "[Video] Lời khuyên cho người lớn tuổi khi đi hành hương Tắc Sậy (Phần 8)",
      "[Video] Khoảnh khắc linh thiêng trong Thánh lễ tại nhà thờ Cha Diệp (Phần 4)",
      "[Video] Cùng đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp (Bản chuẩn) (Phần 6)",
      "[Video] Lắng nghe ca khúc tạ ơn Cha Diệp hay nhất (Phần 5)",
      "[Video] Hành trình xe khách đêm từ Sóc Trăng đi Bạc Liêu (Phần 6)",
      "[Video] Những lưu ý quan trọng khi vào viếng phần mộ Cha Diệp (Phần 2)",
      "[Video] Kiến trúc độc đáo của gian cung thánh nhà thờ Tắc Sậy (Phần 8)",
      "[Video] Phỏng vấn: Niềm tin mãnh liệt của bà con lương dân dành cho Cha (Phần 7)",
      "[Video] Chào buổi sáng Tắc Sậy - Khung cảnh bình minh thanh tịnh (Phần 1)",
      "[Video] Toàn cảnh Nhà thờ Tắc Sậy nhìn từ Flycam hoàng hôn (Phần 1)",
      "[Video] 10 giây bình an: Tiếng chuông nhà thờ Tắc Sậy buổi chiều tà (Phần 9)",
      "[Video] Cận cảnh những bức thư tạ ơn dán đầy quanh mộ Cha (Phần 2)",
      "[Video] Chuyện thật 100%: Lương y nghèo được cứu sống khỏi bạo bệnh thần kỳ (Phần 4)",
      "[Video] Lần đầu đi Tắc Sậy xin ơn: Cần chuẩn bị kinh đọc gì? (Phần 10)",
      "[Video] Hướng dẫn đăng ký xe đi hành hương nhà thờ Cha Diệp ngay trên điện thoại (Phần 5)",
      "[Video] Hướng dẫn điền form gửi Nhật ký Ơn lành trên Website (Phần 8)",
      "[Video] Cảm động: Lời chia sẻ của đoàn người từ An Giang đi từ 4h sáng đến viếng Cha",
      "[Video] Review nhà khách Tắc Sậy: Tiện nghi, sạch sẽ và an bình (Phần 9)",
      "[Video] Sự tích bức tượng Cha Diệp hiền từ tại khuôn viên nhà thờ (Phần 10)",
      "[Video] Theo chân đoàn hành hương Long An khám phá ẩm thực quanh nhà thờ",
      "[Video] Lời khuyên cho người lớn tuổi khi đi hành hương Tắc Sậy (Phần 7)",
      "[Video] Khoảnh khắc linh thiêng trong Thánh lễ tại nhà thờ Cha Diệp (Phần 1)",
      "[Video] Cùng đọc kinh xin ơn Cha Phanxicô Trương Bửu Diệp (Bản chuẩn) (Phần 3)",
      "[Video] Lắng nghe ca khúc tạ ơn Cha Diệp hay nhất (Phần 2)",
      "[Video] Hành trình xe khách đêm từ Đà Lạt đi Bạc Liêu",
      "[Video] Những lưu ý quan trọng khi vào viếng phần mộ Cha Diệp (Phần 1)",
      "[Video] Kiến trúc độc đáo của gian cung thánh nhà thờ Tắc Sậy (Phần 1)",
      "[Video] Phỏng vấn: Niềm tin mãnh liệt của bà con lương dân dành cho Cha (Phần 7)",
      "[Video] Chào buổi sáng Tắc Sậy - Khung cảnh bình minh thanh tịnh (Phần 8)",
      "[Video] Toàn cảnh Nhà thờ Tắc Sậy nhìn từ Flycam hoàng hôn (Phần 1)",
      "[Video] 10 giây bình an: Tiếng chuông nhà thờ Tắc Sậy buổi chiều tà (Phần 2)",
      "[Video] Cận cảnh những bức thư tạ ơn dán đầy quanh mộ Cha (Phần 2)",
      "[Video] Chuyện thật 100%: Lương y nghèo được cứu sống khỏi bạo bệnh thần kỳ (Phần 7)",
      "[Video] Lần đầu đi Tắc Sậy xin ơn: Cần chuẩn bị kinh đọc gì? (Phần 7)"
    ]
  }
];
